[peer]
host = "0.0.0.0"
port = 7012

thread_pool = 15

out_name = "0.0.0.0"
out_sub_name = 0
out_port = 7012

min_ref = 7010
max_ref = 7016

peer_connections = 3
committee_size = 2

keys_path = "/etc/node/keys"

[webserver]
host = "0.0.0.0"
port = 6012
thread_pool = 10

[database]
host = "localhost"
port = 5400
user = "byke"
password = "byke"
db_name = "BYKE"
thread_pool = 2

[nats]
host = "1.bchportal.net"
port = 4222
no_channels = 4
thread_pool = 5
cert_store_path = "/etc/node/cert"